spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce
    username: root
    password: 00449966aia
    driver-class-name: com.mysql.cj.jdbc.Driver
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8080



application:
  security:
    jwt:
      secret-key: GhzUBdHjLZggyiOgo0WjgXc+ppTLf9byKLXW8J5VmOJHD2pXjHIXDyVBJprkSETO
      expiration:  86400000 # day
      #expiration: 300000  # 5 minutes in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days
